#!/usr/bin/env bash
#Redirect

apt-get update -y
apt-get install nginx -y
sudo ufw allow 22
sudo ufw enable
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
