#!/usr/bin/env bash
#Web servers

sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx restart
