#!/usr/bin/env bash
#Bash script that uses ssh to connect to your server with private key
private_key="~/.ssh/school"

user="ubuntu"
server_address="54.157.167.38"

ssh -i "$private_key" "$user@$server_address"
